# .platform.app.yaml

# The name of this application, which must be unique within a project.
name: frontend

# The type key specifies the language and version for your application.
type: 'nodejs:12'

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    post_deploy: |
      npm run build

relationships:
    backend: "backend:http"

# The size of the persistent disk of the application (in MB).
disk: 1024

# The configuration of the application when it is exposed to the web.
web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'public'
            index: ['index.html']
            scripts: false
            allow: true

mounts:
  '/.cache':
      source: local
      source_path: cache
  'public':
      source: local
      source_path: public
