version: 1

info:
  id: platformsh/django3
  name: Django 3
  description: |
      <p>This template deploys the Django 3 application framework on Platform.sh, using the gunicorn application runner.  It also includes a PostgreSQL database connection pre-configured.</p>
      <p>Django is a Python-based web application framework with a built-in ORM.</p>
  tags:
  - Python
  - Framework
  - Django
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGcgY2xpcC1wYXRoPSJ1cmwoI2NsaXAwXzY1MTZfMTQwMDUpIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik02LjM2NTgzIDEyLjMwODlDNi4zNjU4MyAxNC42OTczIDguMTEzNCAxNi4xMjQ1IDEwLjkwOTUgMTUuNDgzN1Y5LjE2MzI4QzguMDg0MjcgOC4yODk1IDYuMzk0OTUgMTAuMDM3MSA2LjM2NTgzIDEyLjMwODlaTTEwLjk5NjkgLTAuMDExNDc0NkgxNC44NDE2VjE4LjE5MjRDMTEuMTQyNSAxOC44MDQxIDcuNjE4MjUgMTkuMTgyNyA1LjA4NDI3IDE3Ljc1NTVDMS44MjIxNCAxNS45NDk3IDEuNTYgMTAuMTUzNiA0LjE1MjIzIDcuNTkwNDdDNS40NjI5MSA2LjI3OTc5IDguMDg0MjcgNS4zNzY4OCAxMC45MDk1IDUuOTU5NFYwLjIyMTU0QzEwLjkwOTUgMC4xMzQxNjIgMTAuODgwNCAwLjAxNzY1MTYgMTAuOTk2OSAtMC4wMTE0NzQ2WiIgZmlsbD0iYmxhY2siLz4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yMS4wNzQ1IDQuMDA3OTVIMTcuMjI5OVYtMC4wMTE0NzQ2SDIxLjA3NDVWNC4wMDc5NVoiIGZpbGw9ImJsYWNrIi8+CjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMjEuMDc0NiA2LjA0Njg4QzIxLjA3NDYgOC44NzIxMiAyMS4wNzQ2IDEwLjkxMSAyMS4wNzQ2IDE0LjM0NzhDMjAuODk5OCAxNy43MjY1IDIwLjk1ODEgMjAuNDM1MiAxOS43MDU2IDIyLjAzNzJDMTkuNDcyNiAyMi4zNTc2IDE4Ljk0ODQgMjIuODIzNiAxOC41MTE1IDIzLjE0NEMxOC4xMzI4IDIzLjQwNjEgMTcuNDYyOSAyMy45ODg2IDE3LjA1NTIgMjMuOTg4NkMxNi42NDc0IDI0LjAxNzcgMTUuNjI4IDIzLjQzNTIgMTUuMTYyIDIzLjIzMTNDMTQuNTUwMyAyMi45NDAxIDEzLjk5NjkgMjIuNTYxNCAxMy4zNTYxIDIyLjM4NjdDMTQuODEyNCAyMS40ODM4IDE2LjIxMDUgMjAuODEzOSAxNi43NjM5IDE4Ljk3ODlDMTcuMjU5IDE3LjM3NyAxNy4yMDA4IDE1LjA3NiAxNy4yMDA4IDEyLjgzMzNDMTcuMjAwOCAxMC42MTk3IDE3LjIwMDggOC4wMjc0NSAxNy4yMDA4IDYuMDc1OTlMMjEuMDc0NiA2LjA0Njg4WiIgZmlsbD0iYmxhY2siLz4KPC9nPgo8ZGVmcz4KPGNsaXBQYXRoIGlkPSJjbGlwMF82NTE2XzE0MDA1Ij4KPHJlY3Qgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSJ3aGl0ZSIvPgo8L2NsaXBQYXRoPgo8L2RlZnM+Cjwvc3ZnPgo=
  notes:
    - heading: "Features"
      content: |
          Python 3.8<br />
          PostgreSQL 12<br />
          Automatic TLS certificates<br />
          Pipfile-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/django3.git@master
  config: null
  files: []
  profile: Django 3
