# Platform.sh Project Initialization Template
#
# This file defines settings and workflow modifications that allow a git
# repository to be deployed to Platform.sh and its white-label partners. A
# project template can be a fully functioning ready-made application or a
# quick-start point for custom development work.
#
# It contains elements that affect the behaviour upon the initialisation of
# a new project (for example minimal plan sizes) as well as elements that
# allow Platform.sh to present it in a user interface (such as the description
# of the project, tags, an icon etc.).
#
# Once provisioned this file has no effects on the running project.  You
# are free to remove it.

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/gatsby-drupal
  # The human-readable name of the template.
  name: Gatsby with Drupal
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: |
     <p>This template builds a two-application project to deploy the Headless CMS pattern using Gatsby as its frontend and Drupal 9 for its backend. The <code>gatsby-source-drupal</code> source plugin is used to pull data from Drupal during the <code>post_deploy</code> hook into the Gatsby Data Layer and build the frontend site. Gatsby utilizes the Platform.sh Configuration Reader library for Node.js to define the backend data source in its configuration. It is intended for you to use as a starting point and modify for your own needs.</p>
     <p>Note that after you have completed the Drupal installation and included a few articles, the project will require a redeploy to build and deploy Gatsby for the first time. See the included README's post-install section for details.</p>
     <p>Gatsby is a free and open source framework based on React that helps developers build statically-generated websites and apps, and Drupal is a flexible and extensible PHP-based CMS framework.</p>
  # A list of tags associated with the template.
  class: demo
  tags:
  - Node.js
  - PHP
  - Microservices
  - Headless CMS
  - CMS
  - Drupal
  - Static Site Generator
  - Symfony
  - Gatsby
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='225' height='225'%3E%3Cg %3E%3Cpath d='M112.5 0A112.5 112.5 0 1 0 225 112.5 112.5 112.5 0 0 0 112.5 0zM24.17 113.67l87.16 87.16a88.35 88.35 0 0 1-87.16-87.16zm108.1 85L26.38 92.73a88.35 88.35 0 0 1 157.54-32.22L171.69 71.3a72.13 72.13 0 0 0-127 16.64l92.38 92.38a72.26 72.26 0 0 0 45.46-50.51h-38.3V112.5h56.61a88.38 88.38 0 0 1-68.57 86.12z' style='fill:%23744c9e' /%3E%3C/g%3E%3C/svg%3E
  # An image URI (either base64-encoded or a URL) representing the template.

  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Features"
      content: |
          Node.js 12<br />
          PHP 7.4<br/>
          MariaDB 10.4<br/>
          Redis 5.0<br/>
          Automatic TLS certificates<br />
          npm-based build for Gatsby<br />
          Composer-based build for Drupal<br />
          Multi-app configuration<br />
          Delayed SSG build (post deploy hook)<br />

plans:
    exclude:
        - small

# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: https://github.com/platformsh-templates/gatsby-drupal.git@master
  config: null
  files: []
  profile: Gatsby with Drupal
