https://{default}/:
    type: upstream
    upstream: app:http

https://{default}/static/:
    type: upstream
    upstream: app:http
    cache:
        enabled: true
        cookies: []

https://{all}/:
    type: upstream
    upstream: app:http

https://{all}/static/:
    type: upstream
    upstream: app:http
    cache:
        enabled: true
        cookies: []
