# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:7.3
build:
    flavor: composer

variables:
    env:
        # Tell Shopware to always install in production-mode.
        SHOPWARE_ENV: 'prod'

# Specify additional PHP extensions that should be loaded.
runtime:
    extensions:
        - ctype
        - dom
        #- hash
        - iconv
        - mbstring
        #- openssl
        #- session
        #- zlib
        - fileinfo


# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        set -e
        export PHP_INI_SCAN_DIR="/app/deploy/php"
        ./deploy/build.sh
    deploy: |
        set -e

        # Install the site if necessary.
        if [ ! -f $PLATFORM_APP_DIR/var/installed ]; then
            # These credentials will be used for the admin user upon installation.
            # You MUST change the admin credentials immediately after setting up your site.
            # Failure to do so is a critical security risk.
            # After the site is installed the values here have no effect.
            export ADMIN_NAME=Admin
            export ADMIN_EMAIL=admin@example.com
            export ADMIN_USERNAME=admin
            export ADMIN_PASSWORD=admin

            # Make the DB credentials available to the installer.
            export DATABASE_URL=`php platformsh-db-url.php`

            $PLATFORM_APP_DIR/bin/console sw:database:setup --steps=import
            $PLATFORM_APP_DIR/bin/console sw:database:setup --steps=setupShop --shop-url="$SHOP_URL"
            $PLATFORM_APP_DIR/bin/console sw:snippets:to:db --include-plugins
            $PLATFORM_APP_DIR/bin/console sw:theme:initialize
            $PLATFORM_APP_DIR/bin/console sw:firstrunwizard:disable
            $PLATFORM_APP_DIR/bin/console sw:plugin:deactivate SwagUpdate
            $PLATFORM_APP_DIR/bin/console sw:admin:create --name="$ADMIN_NAME" --email="$ADMIN_EMAIL" --username="$ADMIN_USERNAME" --password="$ADMIN_PASSWORD" -n

            touch $PLATFORM_APP_DIR/var/installed
        fi;

        ./deploy/deploy.sh

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/custom/plugin":
        source: local
        source_path: "custom/plugin"
    "/engine/Shopware/Plugins/Community":
        source: local
        source_path: "engine/Shopware/Plugins/Community"
    "/files":
        source: local
        source_path: "files"
    "/media":
        source: local
        source_path: "media"
    "/var":
        source: local
        source_path: "var"
    "/web":
        source: local
        source_path: "web"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: ""
            # The front-controller script to send non-static requests to.
            passthru: "/shopware.php"

crons:
    cache-cleanup:
        spec: '30 2 * * *'
        cmd: '/bin/sh /app/deploy/cleanup.sh >> /app/var/log/cleanup.log'

    shopware-cron:
        spec: '*/15 * * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                SHOPWARE_ENV=prod /usr/bin/php -c /app/deploy/php/php.ini bin/console sw:cron:run
            fi

