# The services of the project.
#
# Each service listed will be deployed in its own container as part of your
# Platform.sh project.
#
# See https://docs.platform.sh/configuration/services.html
db:
  type: "mariadb:10.4"
  disk: 2048

cache:
  type: "redis:5.0"

