# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://www.{default}/":
    type: upstream
    upstream: "eleventy:http"

"https://{default}/":
    type: redirect
    to: "https://www.{default}/"

"https://www.backend.{default}/":
    type: upstream
    id: strapi
    upstream: "strapi:http"

"https://backend.{default}/":
    type: redirect
    to: "https://www.backend.{default}/"
