version: 1

info:
  id: platformsh/koa
  name: Koa
  description: |
      <p>This template demonstrates building the Koa framework for Platform.sh.  It includes a minimalist application skeleton that demonstrates how to connect to a MariaDB server for data storage.  It is intended for you to use as a starting point and modify for your own needs.</p>
      <p>Koa is a lightweight web microframework for Node.js.</p>
  tags:
  - Node.js
  - Framework
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='105.6' height='225'%3E%3Cg %3E%3Cpath d='M21 0v149.43L87 75h3l-48.89 55.23L105.6 225h-21L29 143.31l-8.1 9.32V225H0V0z' style='fill:%2316111c' /%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          Node.js 10<br />
          MariaDB 10.2<br />
          Automatic TLS certificates<br />
          npm-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/koa.git@master
  config: null
  files: []
  profile: Koa
