version: 1

info:
  id: platformsh/payara-micro-microprofile
  name: Payara Micro
  description: |
     <p>This project provides a starter kit for Payara Micro projects hosted on Platform.sh.  It includes a minimalist application skeleton that is intended for you to use as a starting point and modify for your own needs, along with the Platform.sh Config Reader to simplify accessing Platform.sh environment variables.</p>
     <p>Payara Micro is an Open Source, lightweight Java EE (Jakarta EE) microservices deployments.</p>
  class: experimental
  tags:
  - Java
  - MicroProfile
  - Maven
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEuMjk0OTIgMTguNDE5NEMxLjI5NDkyIDE4LjQxOTQgMS4yOTQ5MiAxOC40MjQ4IDEuMzAyMzkgMTguNDI2OUwxLjI5NDkyIDE4LjQxOTRaIiBmaWxsPSIjRjA5ODFCIi8+CjxwYXRoIGQ9Ik0yNCAzQzI0IDMgMTcuNTM0OSA0LjYzMiAxNi40MDY0IDYuNTczMzNDMTMuNzAxMyA2LjA5MzMzIDkuMTEyNTMgNi44MTc2IDkuMTEyNTMgNi44MTc2QzkuMTEyNTMgNi44MTc2IDguNjU4MTMgMy44MzYyNyA4Ljk5OTQ3IDNDMS43NDYxMyA2LjQ5MjI3IDAuMjUxNzMzIDEzLjk5NzMgMCAxOC4wNTgxQzAuNjEzNzI4IDE3Ljc5NjQgMS4yNzQxMyAxNy42NjE4IDEuOTQxMzMgMTcuNjYyNEMyLjY4OTMzIDE3LjY1NTkgMy40MjU1OSAxNy44NDg1IDQuMDc0NjcgMTguMjIwM0M0LjEyOTA3IDE4LjE4MTkgMy41MTE0NyAxOS4zNDI0IDIuNjcwOTMgMjAuMzAzNUMyLjI4MjY3IDE5Ljg2NjEgMS41Mjk2IDE4LjkwNCAxLjE4MjkzIDE4LjExNDdDMS4xMzcwNyAxOS4wNzQ3IDEuODIyOTMgMjAuMzk5NSAyLjA5NDkzIDIwLjg4OEwyLjA1MTIgMjAuOTI1M0MxLjc3MjggMjAuNiAwLjg2NCAxOS4zMjg1IDAuNTQ0IDE4LjM4MjRDMC4zOTY4IDE5LjUxODQgMS4yMjQ1MyAyMS4yNzIgMS4yOTA2NyAyMS40MTkyVjIxLjQyNzdDMS4zMTQxMyAyMS40MzYzIDEuMzY0MjcgMjEuNDQ1OSAxLjM1MjUzIDIxLjQ1MTJDMi44MTQ5MyAyMS4zOTQ3IDUuOTY1ODcgMjAuMDcwOSA3LjQxOTczIDE4LjkxNzlDMTIuMjI4MyAxNS4wOTI4IDExLjU3MDEgMTIuNDI4MyAxMS41NzAxIDEyLjQyODNDMTEuNTcwMSAxMi40MjgzIDkuMzUyNTMgMTUuOTY5NiA3LjU5ODkzIDEzLjczNkM2LjIxNzYgMTEuOTgxMyAxMC4zNTk1IDcuOTc2IDE3LjI4NzUgOS4xOTYyN0MyMS4zNDkzIDkuOTA3NzMgMjMuOTA3MiAxMS42NTgxIDIzLjk4NjEgMTEuNzEyNUwyMC4xNDE5IDcuNDY3MkwyNCAzWk0zLjk4ODI3IDE2LjMxMkMzLjY5NDkzIDE2LjY2OTMgMy4zMTQxMyAxNi43MTczIDIuOTk3MzMgMTYuNTM5MkMyLjU3MDY3IDE2LjI5NDkgMy4zMzAxMyAxNC41NDg4IDQuNDE4MTMgMTQuNDY3N0M0LjQxODEzIDE0LjQ2NzcgNC40IDE1LjgwOTYgMy45ODgyNyAxNi4zMTJaTTYuOTEyIDEyLjA0NTNDNi45MTIgMTIuMDQ1MyA3LjIzMiAxMC4xNTMxIDUuMjA1MzMgOC42NjcyQzcuNDQgOS40NDA1MyA3LjY1MTIgMTAuNjY3MiA2LjkxMiAxMi4wNDc1VjEyLjA0NTNaTTcuNTczMzMgMTEuMjQzMkM3LjU3MzMzIDExLjI0MzIgNy44NDIxMyA5LjY2MDI3IDYuMTUyNTMgOC40MTc2QzguMDA4NTMgOS4wNTg2NyA4LjE4NjY3IDEwLjA5MDEgNy41NzMzMyAxMS4yNDMyWk04LjE0MTg3IDEwLjQ0QzguMTQxODcgMTAuNDQgOC4zNTUyIDkuMTYgNi45OTczMyA4LjE2NTg3QzguNDk0OTMgOC42ODUzMyA4LjYzMzYgOS41MTQxMyA4LjEzNzYgMTAuNDRIOC4xNDE4N1pNOC42MzA0IDkuNjkzMzNDOC42Mzg5MyA5LjYzNzg3IDguNzYxNiA4LjcwNjY3IDcuNzYxMDcgNy45NzM4N0M4Ljg5MTczIDguMzYgOS4wMDY5MyA4Ljk5MjUzIDguNjI2MTMgOS42OTAxM0w4LjYzMDQgOS42OTMzM1oiIGZpbGw9IiNGMDk4MUIiLz4KPC9zdmc+Cg==
  notes:
    - heading: "Features"
      content: |
          Java 11<br />
          Automatic TLS certificates<br />
          Maven-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/microprofile-payara.git@master
  config: null
  files: []
  profile: MicroProfile
