version: 1

info:
  id: platformsh/laravel
  name: Laravel
  description: |
      <p>This template provides a basic Laravel skeleton.  It comes pre-configured to use a MariaDB database and Redis for caching and sessions using a Laravel-specific bridge library that runs during Composer autoload.  It is intended for you to use as a starting point and modify for your own needs.</p>
      <p>Laravel is an opinionated, integrated rapid-application-development framework for PHP.</p>
  tags:
  - PHP
  - Laravel
  - Symfony
  - Framework
  image: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIzLjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA4NC4xIDU3LjYiIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDg0LjEgNTcuNjsiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8c3R5bGUgdHlwZT0idGV4dC9jc3MiPgoJLnN0MHtmaWxsOiNGQjUwM0I7fQo8L3N0eWxlPgo8cGF0aCBjbGFzcz0ic3QwIiBkPSJNODMuOCwyNi45Yy0wLjYtMC42LTguMy0xMC4zLTkuNi0xMS45Yy0xLjQtMS42LTItMS4zLTIuOS0xLjJzLTEwLjYsMS44LTExLjcsMS45Yy0xLjEsMC4yLTEuOCwwLjYtMS4xLDEuNgoJYzAuNiwwLjksNyw5LjksOC40LDEybC0yNS41LDYuMUwyMS4yLDEuNWMtMC44LTEuMi0xLTEuNi0yLjgtMS41QzE2LjYsMC4xLDIuNSwxLjMsMS41LDEuM2MtMSwwLjEtMi4xLDAuNS0xLjEsMi45UzE3LjQsNDEsMTcuOCw0MgoJczEuNiwyLjYsNC4zLDJjMi44LTAuNywxMi40LTMuMiwxNy43LTQuNmMyLjgsNSw4LjQsMTUuMiw5LjUsMTYuN2MxLjQsMiwyLjQsMS42LDQuNSwxYzEuNy0wLjUsMjYuMi05LjMsMjcuMy05LjhzMS44LTAuOCwxLTEuOQoJYy0wLjYtMC44LTctOS41LTEwLjQtMTRjMi4zLTAuNiwxMC42LTIuOCwxMS41LTMuMUM4NC4yLDI4LDg0LjQsMjcuNSw4My44LDI2Ljl6IE0zNy41LDM2LjRjLTAuMywwLjEtMTQuNiwzLjUtMTUuMywzLjcKCWMtMC44LDAuMi0wLjgsMC4xLTAuOC0wLjJDMjEuMiwzOS42LDQuNCw0LjgsNC4xLDQuNEMzLjksNCwzLjksMy42LDQuMSwzLjZjMC4yLDAsMTMuNS0xLjIsMTMuOS0xLjJjMC41LDAsMC40LDAuMSwwLjYsMC40CgljMCwwLDE4LjcsMzIuMywxOSwzMi44QzM4LDM2LjEsMzcuOCwzNi4zLDM3LjUsMzYuNHogTTc3LjcsNDMuOWMwLjIsMC40LDAuNSwwLjYtMC4zLDAuOGMtMC43LDAuMy0yNC4xLDguMi0yNC42LDguNAoJYy0wLjUsMC4yLTAuOCwwLjMtMS40LTAuNnMtOC4yLTE0LTguMi0xNEw2OC4xLDMyYzAuNi0wLjIsMC44LTAuMywxLjIsMC4zQzY5LjcsMzMsNzcuNSw0My42LDc3LjcsNDMuOXogTTc5LjMsMjYuMwoJYy0wLjYsMC4xLTkuNywyLjQtOS43LDIuNGwtNy41LTEwLjJjLTAuMi0wLjMtMC40LTAuNiwwLjEtMC43czktMS42LDkuNC0xLjdzMC43LTAuMiwxLjIsMC41YzAuNSwwLjYsNi45LDguOCw3LjIsOS4xCglDODAuMywyNiw3OS45LDI2LjIsNzkuMywyNi4zeiIvPgo8L3N2Zz4K

  notes:
    - heading: "Features"
      content: |
          PHP 7.4<br />
          MariaDB 10.4<br />
          Redis 5.0<br />
          Automatic TLS certificates<br />
          Composer-based build<br />

initialize:
  repository: git://github.com/platformsh-templates/laravel.git@master
  config: null
  files: []
  profile: Laravel
