version: 1

info:
  id: platformsh/quarkus
  name: Quarkus
  description: |
      <p>QuarkusIO, the Supersonic Subatomic Java, promises to deliver small artifacts, extremely fast boot time, and lower time-to-first-request.</p>
      <p>A sample Hello World application is provided as a starting point. It includes a plain REST application.  To use Quarkus with services see the example project (https://github.com/platformsh-examples/quarkus).</p>
  tags:
  - Java
  - MicroProfile
  - Maven
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='224.98' height='225'%3E%3Cdefs%3E%3Cstyle%3E.cls-1%7Bfill:%234695eb%7D.cls-2%7Bfill:%23ff004a%7D%3C/style%3E%3C/defs%3E%3Cg id='Layer_2' data-name='Layer 2'%3E%3Cg id='Layer_1-2' data-name='Layer 1'%3E%3Cpath class='cls-1' d='m147.14 39.54-34.64 20 34.64 20z'/%3E%3Cpath class='cls-2' d='M77.86 39.54v40l34.64-20z'/%3E%3Cpath d='m147.14 79.53-34.64-20-34.64 20 34.64 20z'/%3E%3Cpath class='cls-1' d='M41.34 102.79 76 122.8v-40z'/%3E%3Cpath class='cls-2' d='m76 162.79 34.64-20L76 122.8z'/%3E%3Cpath d='M76 82.8v40l34.64 20v-40z'/%3E%3Cpath class='cls-1' d='M149 162.79v-40l-34.64 20z'/%3E%3Cpath class='cls-2' d='M183.66 102.79 149 82.8v40z'/%3E%3Cpath d='m114.38 142.8 34.64-20v-40l-34.64 20z'/%3E%3Cpath class='cls-1' d='M187.68 0H37.32A37.42 37.42 0 0 0 0 37.32v150.36A37.42 37.42 0 0 0 37.32 225h103l-27.82-67.5-20.16 42.61h-55a12.58 12.58 0 0 1-12.43-12.43V37.32a12.58 12.58 0 0 1 12.41-12.43h150.36a12.58 12.58 0 0 1 12.43 12.43v150.36a12.58 12.58 0 0 1-12.43 12.43h-32.63L165.3 225h22.35A37.43 37.43 0 0 0 225 187.68V37.32A37.43 37.43 0 0 0 187.68 0z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          Java 11<br />
          Automatic TLS certificates<br />
          Maven-based build<br />

initialize:
  repository: git://github.com/platformsh-templates/quarkus.git@master
  config: null
  files: []
  profile: quarkus
