# This file defines services you want available to your application.

mysql:
    type: mysql:10.2
    disk: 256
postgresql:
    type: postgresql:11
    disk: 256
solr:
    type: solr:6.6
    disk: 256
redis:
    type: redis:5.0
elasticsearch:
    type: elasticsearch:5.4
    disk: 256
