version: 1

info:
  id: platformsh/wordpress-bedrock
  name: WordPress (Bedrock)
  description: |
      <p>This template builds WordPress on Platform.sh using the Bedrock boilerplate by Roots with Composer. Plugins and themes should be managed with Composer exclusively. The only modifications made to the standard Bedrock boilerplate have been providing database credentials and main site url parameters via environment variables. With this configuration, the database is automatically configured such that the installer will not ask you for database credentials. While Bedrock provides support to replicate this configuration in a `.env` file for local development, an example Lando configuration file is included as the recommendated method to do so.</p>
      <p>WordPress is a blogging and lightweight CMS written in PHP, and Bedrock is a Composer-based WordPress boilerplate project with a slightly modified project structure and configuration protocol. </p>
  class: starter
  tags:
  - PHP
  - WordPress
  - CMS
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='225' height='225'%3E%3Cdefs%3E%3Cstyle%3E.cls-1%7Bfill:%23525ddc%7D%3C/style%3E%3C/defs%3E%3Cg %3E%3Cg %3E%3Cpath class='cls-1' d='M112.52 74.93V42.67a4.68 4.68 0 0 0-5.48-4.4Q56.94 46.63 6.82 55c-2.25.38-4.33.8-5.69-1.51A6.75 6.75 0 0 1 .05 50.4C0 35.56 0 20.72 0 5.89A6 6 0 0 1 5.92 0h212.81A6 6 0 0 1 225 6.29v43.27a8.1 8.1 0 0 1-6.63 7.7C207.2 59.15 196 61 184.87 62.85l-71.93 12a2.77 2.77 0 0 1-.5 0zM112.47 150.06v31.76a4.68 4.68 0 0 0 5.74 4.86l101.47-17a4.6 4.6 0 0 1 5.33 4.39v45.76c0 2.14-3 5.07-5.14 5.14H6.52c-4 0-6.52-2.47-6.52-6.53V175.7a8.22 8.22 0 0 1 6.88-8q16.62-2.79 33.25-5.54l71.93-12a2.77 2.77 0 0 1 .5 0z'/%3E%3Cpath class='cls-1' d='M112.56 150.15v-37.63l-.08.08 107.04-17.92a4.62 4.62 0 0 1 5.48 4.73v25a8.1 8.1 0 0 1-6.69 7.9c-9.35 1.58-18.71 3.1-28.07 4.66q-35.33 5.88-70.65 11.79c-2.38.4-4.75.87-7.12 1.3zM112.44 74.84v37.76l.08-.08c-9.61 1.56-19.23 3.1-28.83 4.7Q48.58 123.06 13.48 129c-2.47.41-4.94.77-7.4 1.22-3.75.67-6.07-1.2-6.07-5v-25a8.25 8.25 0 0 1 6.37-7.42c10.41-1.8 20.85-3.53 31.28-5.27q35.34-5.88 70.7-11.79c1.4-.23 2.78-.54 4.17-.81z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          PHP 7.4<br />
          MariaDB 10.4<br />
          Automatic TLS certificates<br />
          Composer-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/wordpress-bedrock.git@master
  config: null
  files: []
  profile: WordPress (Bedrock)

