version: 1

info:
  id: platformsh/nuxtjs
  name: NuxtJS
  description: |
      <p>This template builds a simple application using the NuxtJS web framework that can be used as a starting point.</p>
      <p>NuxtJS is an open-source web framework based on Vue.js.</p>
  class: starter
  featured: true
  tags:
  - Node.js
  - Framework
  - Vue.js
  - NuxtJS
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGcgY2xpcC1wYXRoPSJ1cmwoI2NsaXAwXzY2NzRfMTU0NjApIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik03LjMwNDIxIDIwLjM4OUM3LjI4NjQzIDIwLjM1NzEgNy4yNzA3NSAyMC4zMjM5IDcuMjU3MjcgMjAuMjg5OUM3LjE2MTExIDIwLjA2NjMgNy4xMzE0NiAxOS44MTkyIDcuMTcxOTQgMTkuNTc4OUgxLjUwMDQ3TDkuOTI3MTQgNC41OTc2N0wxMi42OTQxIDkuNTEwMjRMMTMuNDk2MiA4LjA3NjMzTDExLjA4NjYgMy43ODUzN0MxMS4wMTgzIDMuNjYxNDcgMTAuNjEwOSAzIDkuOTA5MDEgM0M5LjU4OTAxIDMgOS4xMzY3NCAzLjEzODk3IDguNzY2NjEgMy43OTUwNkwwLjIyNzk0IDE4Ljk1NzNDMC4xNTU0MDcgMTkuMDg4NyAtMC4xOTg3MjcgMTkuNzc4MiAwLjE1MzI3MyAyMC4zODlDMC4zMTMyNzMgMjAuNjY3IDAuNjUzNTQgMjAuOTk3NyAxLjQwMzQxIDIwLjk5NzdIOC41NTAwN0M3LjgwODc0IDIwLjk5NzcgNy40Njc0MSAyMC42NjggNy4zMDQyMSAyMC4zODlaIiBmaWxsPSIjMDBDNThFIi8+CjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNMjMuNzQ3IDE4Ljk1NzNMMTYuNzMwNCA2LjQ3MzI5QzE2LjY1NzkgNi4zNDI5MyAxNi4yNTI2IDUuNjc4MjIgMTUuNTQ3NSA1LjY3ODIyQzE1LjIyNzUgNS42NzgyMiAxNC43NzUyIDUuODE1MDQgMTQuNDA2MiA2LjQ3MTEzTDEzLjQ5ODQgOC4wNzYzNEwxNC4zMDU5IDkuNTEwMjVMMTUuNTU1IDcuMjc2OTdMMjIuNDk2OCAxOS41Nzg5SDE5Ljg1NjhDMTkuODkwNyAxOS43ODIxIDE5Ljg3MiAxOS45OTA2IDE5LjgwMjQgMjAuMTg0M0MxOS43ODc3IDIwLjIyNzIgMTkuNzY5MSAyMC4yNjg3IDE5Ljc0NyAyMC4zMDgyTDE5LjcyNDYgMjAuMzUzNUMxOS4zNjk0IDIwLjk2NDMgMTguNjAyNCAyMC45OTk5IDE4LjQ1MiAyMC45OTk5SDIyLjU4MjJDMjIuNzM0NyAyMC45OTk5IDIzLjQ5OTUgMjAuOTY2NSAyMy44NTM2IDIwLjM1MzVDMjQuMDExNSAyMC4wNzU1IDI0LjEyMzUgMTkuNjA5MSAyMy43NDcgMTguOTU3M1oiIGZpbGw9IiMxMDg3NzUiLz4KPHBhdGggZD0iTTE5LjcyNDYgMjAuMzUzOEwxOS43NDcgMjAuMzA4NkMxOS43NjkxIDIwLjI2OSAxOS43ODc3IDIwLjIyNzYgMTkuODAyNCAyMC4xODQ3QzE5Ljg3MiAxOS45OTEgMTkuODkwNyAxOS43ODI0IDE5Ljg1NjggMTkuNTc5MkMxOS44MTgzIDE5LjM1OTcgMTkuNzQwNiAxOS4xNDkgMTkuNjI3NSAxOC45NTc2TDE0LjMxMDIgOS41MTA1N0wxMy40OTg0IDguMDc2NjZMMTIuNjk0MiA5LjUxMDU3TDcuMzc2ODMgMTguOTU3NkM3LjI3MzM5IDE5LjE1MTIgNy4yMDQwOSAxOS4zNjE2IDcuMTcyMDMgMTkuNTc5MkM3LjEyOTIxIDE5LjgxODggNy4xNTYyNiAyMC4wNjU5IDcuMjQ5OSAyMC4yOTAyQzcuMjYzMzcgMjAuMzI0MyA3LjI3OTA1IDIwLjM1NzQgNy4yOTY4MyAyMC4zODk0QzcuNDU2ODMgMjAuNjY3MyA3Ljc5NzEgMjAuOTk4IDguNTQ2OTcgMjAuOTk4SDE4LjQ0NDZDMTguNjAyNCAyMC45OTggMTkuMzY5NCAyMC45NjQ2IDE5LjcyNDYgMjAuMzUzOFpNMTMuNDk4NCAxMC45NDQ1TDE4LjM1NzEgMTkuNTc5Mkg4LjY0MDgzTDEzLjQ5ODQgMTAuOTQ0NVoiIGZpbGw9ImJsYWNrIi8+CjwvZz4KPGRlZnM+CjxjbGlwUGF0aCBpZD0iY2xpcDBfNjY3NF8xNTQ2MCI+CjxyZWN0IHdpZHRoPSIyNCIgaGVpZ2h0PSIyNCIgZmlsbD0id2hpdGUiLz4KPC9jbGlwUGF0aD4KPC9kZWZzPgo8L3N2Zz4K
  notes:
    - heading: "Features"
      content: |
          Node.js 18<br />
          Automatic TLS certificates<br />
          yarn-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/nuxtjs.git@master
  config: null
  files: []
  profile: NuxtJS
