# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: php:7.4

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
  database: "db:mysql"
  redis: 'cache:redis'

build:
  flavor: none

# Add additional PHP extensions.
runtime:
  extensions:
    - iconv
    - dom
    - simplexml
    - exif
    - opcache
    - imagick
    - fileinfo

variables:
  php:
      memory_limit: 128M

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    "/var":
      source: "local"
      source_path: "var"
    "/web/var":
      source: "local"
      source_path: "web_var"
    "/pimcore":
      source: "local"
      source_path: "pimcore"
    "/web/pimcore":
      source: "local"
      source_path: "web_pimcore"
    "/web/bundles":
      source: "local"
      source_path: "web_bundles"
    "/app/config/local":
      source: "local"
      source_path: "config_local"

# The configuration of app when it is exposed to the web.
web:
  locations:
    '/':
      root: web
      passthru: "/app.php"
      allow: true
      rules:
        '^/videos/(?<resource>.*)$':
          allow: true
        '^/img/(?<resource>.*)$':
          allow: true
        '^/static/(?<resource>.*)$':
          allow: true

# The size of the persistent disk of the application (in MB).
disk: 2048

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e

    bash install-redis.sh 5.1.1

    # This is needed for the installer in the deploy hook.
    curl -sS https://platform.sh/cli/installer | php

    composer install --no-ansi --no-progress --prefer-dist --no-scripts
  deploy: |
    if [ ! -f web/var/.platform.installed ]; then
        platform sql "ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
        # These values are for the inital setup only.  You really need to change them
        # after the site is installed.
        export PIMCORE_INSTALL_ADMIN_USERNAME='admin'
        export PIMCORE_INSTALL_ADMIN_PASSWORD='admin'
        ./vendor/bin/pimcore-install --no-interaction --ignore-existing-config --no-debug
        touch web/var/.platform.installed
    fi

    # Clear env cache
    ./bin/console cache:clear

# The configuration of scheduled execution.
crons:
    pimcore_cron:
        spec: "*/5 * * * *"
        cmd: "bin/console maintenance"
