# The name of this application, which must be unique within a project.
name: 'gatsby'

# The type key specifies the language and version for your application.
type: 'nodejs:14'

relationships:
    drupal: 'drupal:http'

# The hooks that will be triggered when the package is deployed.
hooks:
    # Gatsby's build is delayed to the post_deploy hook, when Drupal is available for requests.
    post_deploy: |
        # We only want to run the full build on master, so development environments can have live preview enabled if desired.
        if [ "$PLATFORM_BRANCH" = master ]; then
           npm run build
        fi
# The size of the persistent disk of the application (in MB).
disk: 1024

# The configuration of the application when it is exposed to the web.
web:
    commands:
        start: |
            # Run a no-op process that uses no CPU resources, since this is a static site on master.
            if [ "$PLATFORM_BRANCH" = master ]; then
               sleep infinity
            # Run development server on non-production environments.
            else
               npm run develop
            fi
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'public'
            index: ['index.html']
            scripts: false
            allow: true

mounts:
    '/.cache':
        source: local
        source_path: cache
    '/.config':
        source: local
        source_path: config
    'public':
        source: local
        source_path: public
