version: 1

info:
  id: platformsh/wagtail
  name: Wagtail
  description: |
      <p>This template builds the Wagtail CMS on Platform.sh, using the gunicorn application runner.  It includes a PostgreSQL database that is configured automatically, and a basic demonstration app that shows how to use it.  It is intended for you to use as a starting point and modify for your own needs.  You will need to run the command line installation process by logging into the project over SSH after the first deploy.</p>
      <p>Wagtail is a web CMS built using the Django framework for Python.</p>
  tags:
  - Python
  - Framework
  - CMS
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAyNSIgaGVpZ2h0PSIyNTAwIiB2aWV3Qm94PSIwIDAgMjU2IDMxNiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiBwcmVzZXJ2ZUFzcGVjdFJhdGlvPSJ4TWlkWU1pZCI+PHBhdGggZD0iTTIxNC43NSA0Ni4yNWE2LjUgNi41IDAgMSAwIDAtMTMgNi41IDYuNSAwIDAgMCAwIDEzem04LjI1IDU2cy04LjI1LTQxLjUtNjIuMjUtMzAuMjVjLTUuNS0xOC43NS00LjUtMzIuNSA3LjUtNDUuMjVDMTg0LjUgOS41IDIxMCAxOSAyMTAgMTlWNC43NUMyMDEgLjc1IDE5Mi41IDAgMTgzIDBjLTM0Ljc1IDAtNTQgMjYtNjIuMjUgNDMuNUwyMyAyMjMuMjUgNTAuNSAyMTggMCAzMTUuNWwzNS4yNS02LjI1IDI3LTc2Ljc1Yzc2LjUgMCAxNzQuNS0yNy41IDE2MC43NS0xMzAuMjV6bTMzLTM0Ljc1bC0yMS41LTIwLjc1LTE3IDIwLjc1SDI1NnpNNzUgMjEwLjI1czIuNS0uNSA3LTEuNSAxMC43NS0yLjUgMTguMjUtNC41YzMuNzUtMSA3Ljc1LTIuMjUgMTItMy43NXM4Ljc1LTMgMTMtNWM0LjUtMS43NSA5LTQgMTMuNS02LjVzOC43NS01LjI1IDEyLjc1LTguNWMxLS43NSAyLTEuNSAzLTIuNWwzLTIuNWMxLjc1LTEuNzUgMy43NS0zLjUgNS41LTUuNSAxLjc1LTEuNzUgMy4yNS0zLjc1IDQuNzUtNS43NWwyLjI1LTMgMS0xLjUgMS0xLjVjLjUtMSAxLjI1LTIgMS43NS0zczEtMiAxLjc1LTNsLjc1LTEuNS43NS0xLjVjLjUtMSAxLTIgMS4yNS0zbDIuMjUtNmMuNS0yIDEuMjUtNCAxLjc1LTUuNzVzLjc1LTMuNzUgMS4yNS01LjI1Yy4yNS0xLjc1LjUtMy4yNS43NS01IC4yNS0xLjUuNS0zIC41LTQuMjUuMjUtMS4yNS4yNS0yLjUuNS0zLjc1LjI1LTQuNS4yNS03IC4yNS03bDQgLjI1cy0uMjUgMi43NS0uNSA3LjI1Yy0uMjUgMS4yNS0uMjUgMi41LS41IDMuNzUtLjI1IDEuNS0uMjUgMy0uNzUgNC41LS4yNSAxLjUtLjc1IDMuMjUtMSA1LS41IDEuNzUtMSAzLjUtMS41IDUuNXMtMS4yNSAzLjc1LTIgNmMtLjc1IDItMS41IDQtMi41IDYuMjVsLTEuNSAzLS43NSAxLjUtLjc1IDEuNWMtLjUgMS0xLjI1IDItMS43NSAzLjI1LS43NSAxLTEuMjUgMi0yIDMtLjI1LjUtLjc1IDEtMSAxLjVsLTEgMS41LTIuMjUgM2MtMS43NSAyLTMuMjUgNC01LjI1IDUuNzUtMS43NSAyLTMuNzUgMy41LTUuNzUgNS41bC0zIDIuNWMtMSAuNzUtMiAxLjUtMy4yNSAyLjI1LTQuMjUgMy04Ljc1IDUuNzUtMTMuMjUgOC4yNS00LjUgMi4yNS05LjI1IDQuNS0xMy43NSA2LjI1cy05IDMuMjUtMTMuMjUgNC41LTguMjUgMi41LTEyLjI1IDMuMjVjLTcuNSAxLjc1LTE0IDMuMjUtMTguNSA0LTQgMS41LTYuNSAyLTYuNSAyeiIvPjwvc3ZnPg==

  notes:
    - heading: "Features"
      content: |
          Python 3.8<br />
          PostgreSQL 12<br />
          Automatic TLS certificates<br />
          Pipfile-based build<br />

initialize:
  repository: git://github.com/platformsh-templates/wagtail.git@master
  config: null
  files: []
  profile: Wagtail
