version: 1

info:
  id: platformsh/spring-mvc-maven-mongodb
  name: Spring MVC, Maven, MongoDB
  description: |
    <p>This template demonstrates building a Spring MVC application. It uses Maven to build the application and deploy it to Platform.sh.</p>
    <p>A sample Hello World application is provided as a starting point.  It includes a MongoDB database, and the sample application shows how to make the database connection. The example code also demonstrates how to access the Platform.sh environment variables using the Platform.sh Config Reader library.</p>
  class: experimental
  tags:
  - Java
  - Spring
  - Maven
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='225' height='224.73'%3E%3Cg %3E%3Cpath d='M204.62 11.69A104.08 104.08 0 0 1 192.6 33 112.83 112.83 0 1 0 35 194.53l4.17 3.68A112.79 112.79 0 0 0 224.37 120c3.07-28.75-5.37-65.09-19.75-108.3zM51.08 195.17a9.65 9.65 0 1 1-1.43-13.55 9.67 9.67 0 0 1 1.43 13.55zm153.06-33.78c-27.84 37.08-87.28 24.61-125.4 26.37 0 0-6.76.4-13.56 1.52 0 0 2.56-1.1 5.84-2.33 26.77-9.33 39.42-11.11 55.68-19.48 30.62-15.56 60.9-49.65 67.2-85.08-11.65 34.09-47 63.39-79.21 75.3-22.06 8.13-61.92 16.05-61.92 16.05l-1.61-.86C24 159.7 23.19 101 72.46 82c21.65-8.3 42.25-3.73 65.54-9.3 24.9-5.92 53.72-24.58 65.45-48.93 13.11 39 28.91 99.86.58 137.64z' style='fill:%236abc45' /%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          Java 11<br />
          MongoDB 3.6<br />
          Automatic TLS certificates<br />
          Maven-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/spring-mvc-maven-mongodb.git@master
  config: null
  files: []
  profile: Spring
