version: 1

info:
  id: platformsh/magento2ce
  name: Magento 2 Community Edition
  description: |
      <p>This template builds Magento 2 CE on Platform.sh.  It includes additional scripts to customize Magento to run effectively in a build-and-deploy environment.  A MariaDB database and Redis cache server come pre-configured and work out of the box.  The installer has been modified to not ask for database information.  Background workers are run using a worker container rather than via cron.</p>
      <p>Magento is a fully integrated ecommerce system and web store written in PHP.  This is the Open Source version.</p>
  tags:
  - PHP
  - Magento
  - CMS
  - Commerce
  related_blog_tags:
  - Magento
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xLjc5OTk5IDYuMDA0NTZMMTIuMjAyNSAwTDIyLjU4NDEgNS45OTQxVjE3Ljk5OEwxOS42MTQ1IDE5LjcwOTVWNy43MTg3TDEyLjE4MTUgMy40MjgyTDQuNzQ4NTUgNy43MTg3TDQuNzY5NTIgMTkuNzE0N0wxLjc5OTk5IDE3Ljk5OFY2LjAwNDU2Wk0xMi4xOTIgMjAuNTc0NEwxMy42NzU1IDE5LjcxMjFWNy43MTg2N0wxNi42NDUgOS40MzI3NVYyMS40Mjg5TDEyLjE4OTQgMjRMNy43MzkwMiAyMS40Mjg5TDcuNzMzNzggOS40MzI3NUwxMC43MDA3IDcuNzE4NjdWMTkuNzJMMTIuMTkyIDIwLjU3NDRaIiBmaWxsPSIjRjI2MzIyIi8+Cjwvc3ZnPgo=
  notes:
    - heading: "Features"
      content: |
          PHP 7.2<br />
          MariaDB 10.2<br />
          Redis 3.2<br />
          Dedicated worker instance for background processing<br />
          Automatic TLS certificates<br />
          Composer-based build<br />

plans:
    exclude:
        - small

initialize:
  repository: https://github.com/platformsh-templates/magento2ce.git@master
  config: null
  files: []
  profile: Magento 2 Community Edition
