# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: "app"

# The runtime the application uses.
type: "ruby:2.7"

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'db:postgresql'

# The size of the persistent disk of the application (in MB).
disk: 1024

# Set environment variables to adjust how Rails will run.
variables:
    env:
        RAILS_ENV: 'production'
        RACK_ENV: 'production'
        RAILS_LOG_TO_STDOUT: true
        BUNDLE_ERROR_ON_STDERR: 1
        RAILS_TMP: /tmp
        EXECJS_RUNTIME: 'Node'
        NODE_ENV: 'production'
        # Update these for your desired NVM and Node versions.
        NVM_VERSION: v0.37.2
        NODE_VERSION: v14.15.1

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    "/log":
        source: local
        source_path: log
    "/tmp":
        source: local
        source_path: tmp

dependencies:
    nodejs:
        yarn: "*"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # The build hook turns what is in source control into the deployable application.
    build: |
        set -e

        # Install nvm to use newer version of node.
        # Webpacker requires Node.js ">=10.17.0"
        unset NPM_CONFIG_PREFIX
        export NVM_DIR="$PLATFORM_APP_DIR/.nvm"
        # install.sh will automatically install NodeJS based on the presence of $NODE_VERSION
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

        gem install --no-document bundler:2.1.4
        bundle config set without 'development test'
        bundle config deployment true
        bundle install
        RAILS_ENV=production bundle exec rake assets:precompile
    # The deploy hook runs after your application has been deployed and started.
    deploy: |
        bundle exec rails db:migrate
# The configuration of the application when running.
web:
    upstream:
        # Send requests to the app server through a unix socket, whose location
        # will be defined in an environment variable named SOCKET.
        socket_family: "unix"

    commands:
        start: 'bundle exec unicorn -l $SOCKET'
