"https://{default}/":
    type: upstream
    upstream: "directus:http"
    cache:
        enabled: true
        default_ttl: 0
        cookies: ['*']
        headers: ['Accept', 'Accept-Language']

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
