version: 1

info:
  id: platformsh/eleventy-strapi
  name: Eleventy with Strapi
  description: |
      <p>This template deploys a two application project on Platform.sh: one for a frontend static site generator, Eleventy, and the other for a backend headless CMS, Strapi. Like our other "decoupled" templates, Eleventy's build is delayed until the <code>post_deploy</code> hook, at which point the backend Strapi content data becomes available to query using GraphQL. That data then is reformatted into "Blogs" on the frontend. Both applications utilize the Platform.sh Configuration Reader library for Node.js. It is intended for you to use as a starting point and modify for your own needs.</p>
      <p>Note that there are several setup steps required after the first deploy. An <code>article</code> content type has already been committed, but you will still need to follow the post deploy instructions to add content and define permissions for Eleventy to consume it.</p>
      <p>Eleventy is a static site generator written in Node.js, and Strapi is a headless CMS framework also written in Node.js.</p>

  tags:
  - Node.js
  - CMS
  - API
  - Headless CMS
  image: data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeD0iMCIgeT0iMCIgdmlld0JveD0iMCAwIDE1NjkuNCAyMTg2IiB4bWw6c3BhY2U9InByZXNlcnZlIiBhcmlhLWhpZGRlbj0idHJ1ZSIgZm9jdXNhYmxlPSJmYWxzZSI+PHN0eWxlPi5zdDB7ZmlsbDojZmZmO3N0cm9rZTojZmZmO3N0cm9rZS13aWR0aDoyODtzdHJva2UtbWl0ZXJsaW1pdDoxMH08L3N0eWxlPjxnPjxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik01NjIuMiAxNDEwLjFjLTkgMC0xMy41LTEyLTEzLjUtMzYuMVY3NzguOWMwLTExLjUtMi4zLTE2LjktNy0xNi4yLTI4LjQgNy4yLTQyLjcgMTAuOC00My4xIDEwLjgtNy45LjctMTEuOC03LjItMTEuOC0yMy43di01MS43YzAtMTQuMyA0LjMtMjIuNCAxMi45LTI0LjJsMTQyLjItMzYuNmMxLjEtLjMgMi43LS41IDQuOC0uNSA3LjkgMCAxMS44IDguNCAxMS44IDI1LjN2NzEyYzAgMjQuMS00LjcgMzYuMS0xNCAzNi4xbC04Mi4zLS4xek05MzAuNSAxNDExLjJjLTE0LjQgMC0yNi44LTEtMzcuNC0zLTEwLjYtMi0yMS42LTYuNS0zMy4xLTEzLjVzLTIwLjktMTYuNi0yOC4zLTI4LjgtMTMuNC0yOS4zLTE4LTUxLjItNy00Ny45LTctNzguMVY5NjAuNGMwLTcuMi0yLTEwLjgtNS45LTEwLjhoLTMzLjRjLTkgMC0xMy41LTguNi0xMy41LTI1Ljh2LTI5LjFjMC0xNy42IDQuNS0yNi40IDEzLjUtMjYuNGgzMy40YzMuOSAwIDUuOS00LjggNS45LTE0LjVsOS43LTIwOS41YzEuMS0xOSA1LjctMjguNSAxNC0yOC41aDUzLjljOSAwIDEzLjUgOS41IDEzLjUgMjguNXYyMDkuNWMwIDkuNyAyLjEgMTQuNSA2LjUgMTQuNUg5NzNjOSAwIDEzLjUgOC44IDEzLjUgMjYuNHYyOS4xYzAgMTcuMi00LjUgMjUuOC0xMy41IDI1LjhoLTY4LjljLTIuNSAwLTQuMi42LTUuMSAxLjktLjkgMS4yLTEuMyA0LjItMS4zIDguOXYyNzcuOWMwIDIwLjggMS4zIDM4LjIgNCA1MnM2LjYgMjQgMTEuOCAzMC40IDEwLjQgMTAuOCAxNS42IDEyLjljNS4yIDIuMiAxMS42IDMuMiAxOS4xIDMuMmgzOC4yYzkuNyAwIDE0LjUgNi43IDE0LjUgMTkuOXYzMi4zYzAgMTQuNy01LjIgMjIuMS0xNS42IDIyLjFsLTU0LjguMXpNMTEzNy4yIDE0NzUuOGM4LjIgMCAxNS40LTYuNyAyMS41LTIwLjJzOS4yLTMyLjYgOS4yLTU3LjRjMC01LjgtMy42LTI1LjctMTAuOC01OS44bC0xMDUuNi00MzguOWMtLjctNS0xLjEtOS0xLjEtMTEuOSAwLTEyLjkgMi43LTE5LjQgOC4xLTE5LjRoNjUuMmM1IDAgOS4xIDEuNyAxMi40IDUuMXM1LjggMTAuMyA3LjUgMjAuN2w3MCAzNzAuNWMxLjQgNC4zIDIuMyA2LjUgMi43IDYuNSAxLjQgMCAyLjItMiAyLjItNS45bDU0LjktMzY5LjVjMS40LTEwLjggMy43LTE4IDYuNy0yMS44czYuOS01LjcgMTEuNi01LjdoNDUuMmM2LjEgMCA5LjIgNyA5LjIgMjEgMCAzLjItLjQgNy40LTEuMSAxMi40bC05NS45IDQ5OS4zYy03LjUgNDEuMy0xNS44IDcyLjktMjQuOCA5NC44cy0xOSAzNi44LTMwLjIgNDQuN2MtMTEuMSA3LjktMjUuOCAxMi00NC4yIDEyLjRoLTUuNGMtMjkuMSAwLTQ4LjgtNy43LTU5LjItMjMuMi0yLjktMy4yLTQuMy0xMS41LTQuMy0yNC44IDAtMjYuNiA0LjMtMzkuOSAxMi45LTM5LjkuNyAwIDcuMiAxLjggMTkuNCA1LjQgMTIuNCAzLjggMjAuMyA1LjYgMjMuOSA1LjZ6Ij48L3BhdGg+PGc+PHBhdGggY2xhc3M9InN0MCIgZD0iTTI5MS4yIDE0MTEuMWMtOSAwLTEzLjUtMTItMTMuNS0zNi4xVjc3OS45YzAtMTEuNS0yLjMtMTYuOS03LTE2LjItMjguNCA3LjItNDIuNyAxMC44LTQzLjEgMTAuOC03LjkuNy0xMS44LTcuMi0xMS44LTIzLjd2LTUxLjdjMC0xNC4zIDQuMy0yMi40IDEyLjktMjQuMkwzNzEgNjM4LjJjMS4xLS4zIDIuNy0uNSA0LjgtLjUgNy45IDAgMTEuOCA4LjQgMTEuOCAyNS4zdjcxMmMwIDI0LjEtNC43IDM2LjEtMTQgMzYuMWgtODIuNHoiPjwvcGF0aD48L2c+PC9nPjwvc3ZnPg==

  notes:
    - heading: "Features"
      content: |
          Node.js 12 & 14<br />
          PostgreSQL 12<br />
          Automatic TLS certificates<br />
          yarn-based build<br />
          Multi-app configuration<br />
          Delayed SSG build (post deploy hook)<br />

plans:
    exclude:
        - small

initialize:
  repository: git://github.com/platformsh-templates/eleventy-strapi.git@master
  config: null
  files: []
  profile: Eleventy with Strapi
