#########################
# Django 4 using pip
##########################
# Container configuration.

#   The name of this app. Must be unique within a project.
name: 'app'

#   The runtime the application uses.
type: 'python:3.11'

##########################
# Builds and variables

hooks:
    build: |
        set -eu

        # Download the latest version of pip
        python3.11 -m pip install --upgrade pip

        # Install dependencies
        pip install -r requirements.txt

##########################
# Web configuration

# The configuration of the application when it is exposed to the web.
web:
    commands:
        start: "python server.py"

##########################
# Services

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "db:mysql"
    rediscache: "cache:redis"

##########################
# Data and mounts

# The size of the persistent disk of the application (in MB).
disk: 1024

##########################
# Internal maintenance

source:
    operations:
        auto-update:
            command: |
              curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
