# Platform.sh Project Initialization Template
#
# This file defines settings and workflow modifications that allow a git
# repository to be deployed to Platform.sh and its white-label partners. A
# project template can be a fully functioning ready-made application or a
# quick-start point for custom development work.
#
# It contains elements that affect the behaviour upon the initialisation of
# a new project (for example minimal plan sizes) as well as elements that
# allow Platform.sh to present it in a user interface (such as the description
# of the project, tags, an icon etc.).
#
# Once provisioned this file has no effects on the running project.  You
# are free to remove it.

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/elastic-apm
  # The human-readable name of the template.
  name: Elastic APM with Kibana
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: |
    <p>This template builds Elastic APM (Application Performance Monitoring) with a Kibana front-end.
      It is intended as a complete self-contained monitoring solution, although authentication needs to be
        configured for your specific application.</p>

  class: experimental
  # A list of tags associated with the template.
  tags:
  - Elasticsearch
  # An image URI (either base64-encoded or a URL) representing the template.
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPGcgY2xpcC1wYXRoPSJ1cmwoI2NsaXAwXzY1MTZfMTQxMzkpIj4KPHBhdGggZD0iTTE3LjUzIDguMzk5OUgxMS4yNkMxMS4yNiA4LjU0OTkgMTEuMzUgOC42OTk5IDExLjM4IDguODE5OUMxMS41ODc3IDkuNTU0MzQgMTEuNzE4NCAxMC4zMDg0IDExLjc3IDExLjA2OTlDMTEuNzcgMTEuMzY5OSAxMS43NyAxMS42OTk5IDExLjc3IDExLjk5OTlDMTEuNzcgMTIuMjk5OSAxMS43NyAxMi42Mjk5IDExLjc3IDEyLjkyOTlDMTEuNzE4NCAxMy42OTE0IDExLjU4NzcgMTQuNDQ1NSAxMS4zOCAxNS4xNzk5QzExLjM4IDE1LjMyOTkgMTEuMjkgMTUuNDc5OSAxMS4yNiAxNS41OTk5SDE3LjUzQzE4LjQ4NDggMTUuNTk5OSAxOS40MDA1IDE1LjIyMDYgMjAuMDc1NiAxNC41NDU1QzIwLjc1MDcgMTMuODcwNCAyMS4xMyAxMi45NTQ3IDIxLjEzIDExLjk5OTlDMjEuMTMgMTEuMDQ1MSAyMC43NTA3IDEwLjEyOTQgMjAuMDc1NiA5LjQ1NDMyQzE5LjQwMDUgOC43NzkxOSAxOC40ODQ4IDguMzk5OSAxNy41MyA4LjM5OTlaIiBmaWxsPSIjMDBBOUU1Ii8+CjxwYXRoIGQ9Ik0xMS43NyAxMi45Mjk5QzExLjc3IDEyLjYyOTkgMTEuNzcgMTIuMjk5OSAxMS43NyAxMS45OTk5QzExLjc3IDExLjY5OTkgMTEuNzcgMTEuMzY5OSAxMS43NyAxMS4wNjk5QzExLjcxODQgMTAuMzA4NCAxMS41ODc3IDkuNTU0MzQgMTEuMzggOC44MTk5QzExLjM4IDguNjY5OSAxMS4yOSA4LjUxOTkgMTEuMjYgOC4zOTk5SDEuNTRDMC44MiAxMC43NDU5IDAuODIgMTMuMjUzOSAxLjU0IDE1LjU5OTlIMTEuMjNDMTEuMjMgMTUuNDQ5OSAxMS4zMiAxNS4yOTk5IDExLjM1IDE1LjE3OTlDMTEuNTY3OSAxNC40NDY1IDExLjcwODYgMTMuNjkyNSAxMS43NyAxMi45Mjk5WiIgZmlsbD0iIzM1MzUzNSIvPgo8cGF0aCBkPSJNMTguNjEgMTYuOEgxMC44MUMxMC41NzYyIDE3LjMyODQgMTAuMzA1NSAxNy44Mzk3IDkuOTk5OTkgMTguMzNDOS41NDQ5MiAxOS4wNTMgOS4wMTE3MiAxOS43MjM3IDguNDA5OTkgMjAuMzNMNy43Nzk5OSAyMC45M0M3LjM0NjczIDIxLjMxOTkgNi44ODU0OSAyMS42Nzc1IDYuMzk5OTkgMjJDOC4zNTM1OCAyMy4zMDUyIDEwLjY1MDUgMjQuMDAxMiAxMyAyNEMxNC45Nzc4IDI0LjAwMyAxNi45MjU3IDIzLjUxNyAxOC42NzAzIDIyLjU4NTRDMjAuNDE1IDIxLjY1MzcgMjEuOTAyMyAyMC4zMDUzIDIzIDE4LjY2QzIyLjQyOTkgMTguMDcyMSAyMS43NDc2IDE3LjYwNDUgMjAuOTkzNiAxNy4yODVDMjAuMjM5NSAxNi45NjU1IDE5LjQyOSAxNi44MDA2IDE4LjYxIDE2LjhaIiBmaWxsPSIjMDBCRkIzIi8+CjxwYXRoIGQ9Ik0xMCAxOC4zM0MxMC4zMDU1IDE3LjgzOTcgMTAuNTc2MiAxNy4zMjg0IDEwLjgxIDE2LjhIMkMyLjkyNjY0IDE4LjkyNjMgNC40NTY0MSAyMC43MzQzIDYuNCAyMkM2Ljg3ODMyIDIxLjY5MjggNy4zMzkwNCAyMS4zNTg5IDcuNzggMjFDNy45OSAyMC44MiA4LjIgMjAuNjEgOC40MSAyMC40QzkuMDA0NzIgMTkuNzYyMyA5LjUzNzE0IDE5LjA2OTEgMTAgMTguMzNaIiBmaWxsPSIjMDE5QjhGIi8+CjxwYXRoIGQ9Ik04LjM4IDMuNjNDOC4xNyAzLjQyIDggMy4yNCA3Ljc1IDNDNy4zMTQ0MSAyLjYzNDIyIDYuODUzMjMgMi4zMDAwNCA2LjM3IDJDNC40NTgwOSAzLjI5MzIxIDIuOTQ0NzMgNS4wOTQgMiA3LjJIMTAuNzhDMTAuNTU1OSA2LjY3MjQ5IDEwLjI5NTIgNi4xNjEyNSAxMCA1LjY3QzkuNTQ1NjggNC45MjYxNiA5LjAwMTU5IDQuMjQxMDEgOC4zOCAzLjYzWiIgZmlsbD0iI0Y5QjExMCIvPgo8cGF0aCBkPSJNMTMgMS4zMTg1NGUtMDVDMTAuNjUwNSAtMC4wMDExODY0OSA4LjM1MzU4IDAuNjk0ODYzIDYuMzk5OTkgMi4wMDAwMUM2Ljg3ODMxIDIuMzA3MzEgNy4zMzkwMyAyLjY0MTE3IDcuNzc5OTkgMy4wMDAwMUM3Ljk4OTk5IDMuMTgwMDEgOC4xOTk5OSAzLjM5MDAxIDguNDA5OTkgMy42MDAwMUM5LjAxNTg2IDQuMjI4MjcgOS41NDkyMSA0LjkyMjYzIDkuOTk5OTkgNS42NzAwMUMxMC4zMDU1IDYuMTYwNDEgMTAuNTc2MiA2LjY3MTY3IDEwLjgxIDcuMjAwMDFIMTguNjFDMTkuNDI5IDcuMTk5NDggMjAuMjM5NSA3LjAzNDU5IDIwLjk5MzYgNi43MTUwOUMyMS43NDc2IDYuMzk1NiAyMi40Mjk5IDUuOTI4IDIzIDUuMzQwMDFDMjEuOTAyMyAzLjY5NDc2IDIwLjQxNSAyLjM0NjM0IDE4LjY3MDMgMS40MTQ3QzE2LjkyNTcgMC40ODMwNTQgMTQuOTc3OCAtMC4wMDI5MTg0NCAxMyAxLjMxODU0ZS0wNVoiIGZpbGw9IiNGRUQxMEEiLz4KPC9nPgo8ZGVmcz4KPGNsaXBQYXRoIGlkPSJjbGlwMF82NTE2XzE0MTM5Ij4KPHJlY3Qgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSJ3aGl0ZSIvPgo8L2NsaXBQYXRoPgo8L2RlZnM+Cjwvc3ZnPgo=
  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Apps & Services"
      content: "Elasticsearch 7.2"


# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: https://github.com/platformsh-templates/elastic-apm.git@master
  config: null
  files: []
  profile: Elastic APM with Kibana
