name: app

type: 'nodejs:18'

build:
    flavor: none

hooks:
    build: |
        corepack yarn install
        corepack yarn build

web:
    commands:
        start: "node .output/server/index.mjs"

source:
    operations:
        auto-update:
            command: |
                curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
