version: 1

info:
  id: platformsh/pimcore
  name: Pimcore
  description: |
      <p>This template builds Pimcore 5 on Platform.sh.  It comes pre-installed with a MariaDB database connecting through Doctrine and Redis for caching via a custom configuration file.  It will self-install on the first deploy.</p>
      <p>Pimcore is a Symfony-based Digital Experience Platform.</p>
  tags:
  - PHP
  - Symfony
  - PIM
  - CMS

  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='225' height='131.25'%3E%3Cg data-name='Layer 2'%3E%3Cpath d='M178.13 18.75a47.28 47.28 0 0 0-39.07 20.94l-34.37 51.87a46.88 46.88 0 1 1-39.07-72.81 46.45 46.45 0 0 1 38.76 20.63l6.25 9.37 11.24-16.87-1.56-2.5a65.62 65.62 0 1 0-54.69 101.87 65 65 0 0 0 54.69-29.38l12.82-19.37 5.93 9.06a46.88 46.88 0 1 0 39.07-72.81zm0 75a27.83 27.83 0 0 1-23.44-12.81l-10.32-15.32L154.69 50a28.3 28.3 0 0 1 23.44-12.5 28.13 28.13 0 0 1 0 56.25z' style='fill:%236428b4' data-name='Layer 1'/%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          PHP 7.4<br />
          MariaDB 10.4<br />
          Redis 5<br />
          Automatic TLS certificates<br />
          Composer-based build<br />

initialize:
  repository: git://github.com/platformsh-templates/pimcore.git@master
  config: null
  files: []
  profile: Pimcore
