version: 1

info:
  id: platformsh/typo3
  name: TYPO3
  description: |
      <p>This template builds the TYPO3 CMS for Platform.sh.  It comes pre-configured with MariaDB for storage and Redis for caching.  A command line installer will automatically initialize the site on first deploy.</p>
      <p>TYPO3 is a PHP-based Content Management System</p>
  tags:
  - PHP
  - CMS
  - Typo3
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yMy43MDAxIDIuODAwMDFDMjMuNzAwMSAwLjYwMDAwMSAxOS45MDAxIDAgMTYuMDAwMSAwQzE0LjQwMDEgMCAxMy43MDAxIDAuMzAwMDAxIDEzLjgwMDEgMS45QzEzLjgwMDEgNS41MDAwMSAxNy4wMDAxIDEyLjYgMTkuNTAwMSAxMi42QzIwLjkwMDEgMTIuNiAyMy43MDAxIDcuMjAwMDIgMjMuNzAwMSAyLjgwMDAxWk0xNi45IDE2LjdDMTcuMyAxNi43IDE3LjUgMTYuNyAxNy45IDE2LjZDMTUuMiAyMC45IDEyIDI0IDEwLjEgMjRDNS45MDAwMiAyNCAwIDExLjQ5OTkgMCA1Ljg5OTkyQzAgNC45OTk5MiAwLjIgNC4zOTk5MiAwLjUwMDAwMSAzLjg5OTkyQzEuOSAyLjE5OTkyIDYuNDAwMDIgMC43OTk5MTIgMTAuMSAwLjM5OTkxMUM5LjcwMDAyIDAuNzk5OTEyIDkuNDAwMDIgMS4xOTk5MSA5LjQwMDAyIDIuNDk5OTJDOS40MDAwMiA1Ljk5OTkyIDEzLjkgMTYuNyAxNi45IDE2LjdaIiBmaWxsPSIjRkY4NzAwIi8+Cjwvc3ZnPgo=
  notes:
    - heading: "Features"
      content: |
          PHP 7.4<br />
          MariaDB 10.4<br />
          Redis 5.0<br />
          Automatic TLS certificates<br />
          Composer-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/typo3.git@master
  config: null
  files: []
  profile: TYPO3
