version: 1

info:
  id: platformsh/backdrop
  name: Backdrop
  description: |
    <p>This template deploys a Backdrop CMS site, with the entire site committed to Git.  It comes configured for MariaDB, the most popular database used with Backdrop.  It supports a quick web installation to configure the site.</p>
    <p>Backdrop is a PHP-based CMS, originally forked from Drupal 7.</p>
  tags:
  - PHP
  - CMS
  image: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCiA8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyINCiB3aWR0aD0iNDcwIiBoZWlnaHQ9IjQ3MCI+DQo8cmVjdCBmaWxsPSJibGFjayIgd2lkdGg9IjQ3MCIgaGVpZ2h0PSI0NzAiLz4NCjxwYXRoIGZpbGw9IndoaXRlIiBkPSJtIDIzNSw0NzAgMCwtMjM1IDIzNSwwIHoiLz4NCjwvc3ZnPg0K

  notes:
    - heading: "Features"
      content: |
          PHP 7.3<br />
          MariaDB 10.4<br />
          Drush included<br />
          Automatic TLS certificates<br />

initialize:
  repository: git://github.com/platformsh-templates/backdrop.git@master
  config: null
  files: []
  profile: Backdrop
