# Platform.sh Project Initialization Template
#
# This file defines settings and workflow modifications that allow a git
# repository to be deployed to Platform.sh and its white-label partners. A
# project template can be a fully functioning ready-made application or a
# quick-start point for custom development work.
#
# It contains elements that affect the behaviour upon the initialisation of
# a new project (for example minimal plan sizes) as well as elements that
# allow Platform.sh to present it in a user interface (such as the description
# of the project, tags, an icon etc.).
#
# Once provisioned this file has no effects on the running project.  You
# are free to remove it.

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/symfony3
  # The human-readable name of the template.
  name: Symfony 3
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: Symfony is a loosely coupled PHP web application framework.
  # A list of tags associated with the template.
  tags:
  - PHP
  - Symfony
  - Framework
  # An image URI (either base64-encoded or a URL) representing the template.
  image: data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHZpZXdCb3g9IjAgMCA0MCA0MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00MCAyMEM0MCAzMS4wNDU3IDMxLjA0NTcgNDAgMjAgNDBDOC45NTQzIDQwIDAgMzEuMDQ1NyAwIDIwQzAgOC45NTQzIDguOTU0MyAwIDIwIDBDMzEuMDQ1NyAwIDQwIDguOTU0MyA0MCAyMFpNMjMuNTg2IDEwLjEyNjJDMjQuOTA0MSA4LjU3OTE0IDI2LjY3NTIgNy40NjA5OSAyOC43MDQxIDcuMzkwMjJDMzAuNzMxOCA3LjMyMzc2IDMyLjI2MzUgOC4yNDE5MSAzMi4zMTM0IDkuNjk0ODNDMzIuMzMzNyAxMC4zMTMzIDMxLjk3OCAxMS41MTc2IDMwLjc0MTEgMTEuNTU3NkMyOS44MTc0IDExLjU5MDggMjkuMTc4NiAxMS4wMzg4IDI5LjE0OTcgMTAuMTk4OEMyOS4xMzk4IDkuODkwNTIgMjkuMjE5MiA5LjYyMjIyIDI5LjQyOTcgOS4zMDcxNEMyOS40NjUyIDkuMjM3NzIgMjkuNDk1OSA5LjE3ODkgMjkuNTIyMyA5LjEyODE4QzI5LjY1IDguODgzNTIgMjkuNjc5MiA4LjgyNzU5IDI5LjY3NDYgOC42ODEzQzI5LjY1NjEgOC4xNTI2OCAyOC44NTY3IDguMTMxNzYgMjguNjM4MyA4LjE0MjgzQzI1LjY0MDcgOC4yNDEyOSAyNC44NTA2IDEyLjI4ODEgMjQuMjEgMTUuNTc3OUwyMy44OTYxIDE3LjMxMjdDMjUuNjIyMyAxNy41NjYyIDI2Ljg0ODEgMTcuMjU0MiAyNy41MzE4IDE2LjgxMThDMjguMTE0MSAxNi40MzQ2IDI3Ljg5MzQgMTYuMDUwOCAyNy42NjI1IDE1LjY0ODlDMjcuNTExNiAxNS4zODY0IDI3LjM1NjMgMTUuMTE2MiAyNy40MTc0IDE0LjgzNTFDMjcuNTc1NSAxNC4xMTAyIDI4LjIzNCAxMy43NjEzIDI4Ljc1ODMgMTMuNzQ2NUMyOS40OTA2IDEzLjcyOTMgMzAuMDEzNyAxNC40ODg3IDI5Ljk5NzEgMTUuMjYwNEMyOS45NzE4IDE2LjUzNTQgMjguMjc4OSAxOC4yODg3IDI0Ljg5NDMgMTguMjE3M0MyNC40ODIgMTguMjA3NCAyNC4xMDI5IDE4LjE3OTEgMjMuNzQ4NCAxOC4xMzY3TDIzLjExMDMgMjEuNjYxTDIzLjA5MjkgMjEuNzQyM0MyMi41MjMgMjQuNDA0MyAyMS43NTExIDI4LjAxMDEgMTkuMDYxMSAzMS4xNTk0QzE2LjcyNjMgMzMuOTM0OCAxNC4zNTcxIDM0LjM2NjggMTMuMjk2MSAzNC40MDMxQzExLjMxMTUgMzQuNDcwMiA5Ljk5NTIxIDMzLjQxMTggOS45NDc4MiAzMS45OTk0QzkuOTAyMjkgMzAuNjMyMSAxMS4xMTIxIDI5Ljg4NSAxMS45MDYgMjkuODU3OUMxMi45NjU3IDI5LjgyMjggMTMuNjk4NiAzMC41OTAyIDEzLjcyNjkgMzEuNDc1MUMxMy43NTM0IDMyLjIyNDEgMTMuMzYyNiAzMi40NTc5IDEzLjEwNDEgMzIuNTk4OEMxMy4wNzkgMzIuNjE5MSAxMy4wNTE5IDMyLjYzOTQgMTMuMDI0MiAzMi42NjAyQzEyLjg2MTIgMzIuNzgyNyAxMi42NzI0IDMyLjkyNDQgMTIuNjgxNCAzMy4xODg0QzEyLjY4NzUgMzMuMzIwMSAxMi44Mjk3IDMzLjYyMjggMTMuMjY5NyAzMy42MDkzQzE0LjA4MzMgMzMuNTgxMyAxNC42MzE1IDMzLjE5MDcgMTUuMDE5MSAzMi45MTQ2QzE1LjAzMTQgMzIuOTA1OCAxNS4wNDM1IDMyLjg5NzIgMTUuMDU1NSAzMi44ODg3QzE2Ljk4OTEgMzEuMjc3IDE3LjczMzEgMjguNDY5NiAxOC43MDc4IDIzLjM1N0wxOC45MTA5IDIyLjExNzZMMTguOTI3MiAyMi4wMzY0QzE5LjI1NTggMjAuMzk1MiAxOS42MjEgMTguNTcxOSAyMC4xNzQ5IDE2Ljc1NTFDMTkuNzU5NCAxNi40NDI2IDE5LjM5NDYgMTYuMTA3MiAxOS4wMzY0IDE1Ljc3NzdDMTguMjE4OSAxNS4wMjYgMTcuNDM1NCAxNC4zMDU2IDE2LjE2MDcgMTMuOTU5NEMxNC45MDQ3IDEzLjYxNzkgMTQuMTM4IDEzLjkwODQgMTMuNTk5NSAxNC41ODlDMTIuOTYxNCAxNS4zOTU4IDEzLjE3MzEgMTYuNDQ1NiAxMy43ODk3IDE3LjA2MTZMMTQuODA3NSAxOC4xODcxQzE2LjA1NjcgMTkuNjMwMiAxNi43Mzg2IDIwLjc1MjEgMTYuNDgyIDIyLjI2MjJDMTYuMDc0NiAyNC42NzMzIDEzLjIwMjYgMjYuNTIxOSA5LjgwNzUyIDI1LjQ3ODhDNi45MDk2NyAyNC41ODUzIDYuMzY4NzUgMjIuNTMzNiA2LjcxNjQ0IDIxLjQwMzFDNy4wMjI5IDIwLjQwODEgNy44MTM2NyAyMC4yMjA0IDguNTg2NTkgMjAuNDU3M0M5LjQxNDkgMjAuNzEyNyA5LjczODU5IDIxLjcxODggOS41MDE2NyAyMi40OTI0QzkuNDk5MjcgMjIuNDk5OCA5LjQ5Njc0IDIyLjUwNzYgOS40OTQwNiAyMi41MTU5QzkuNDY3MjMgMjIuNTk5MSA5LjQyNTQzIDIyLjcyODggOS4zNDU5OCAyMi44OTY3QzkuMzA2MTkgMjIuOTg2MyA5LjI1MjA2IDIzLjA3MDggOS4xOTY4OSAyMy4xNTdDOS4xMTk3OSAyMy4yNzc0IDkuMDQwNjYgMjMuNDAxIDguOTk1ODIgMjMuNTQ1OUM4LjgwOTM2IDI0LjE1MzMgOS42NDEzNiAyNC41ODQ3IDEwLjIyMDQgMjQuNzYxM0MxMS41MTcxIDI1LjE2MTMgMTIuNzgxMSAyNC40ODI1IDEzLjEwMjkgMjMuNDMzOUMxMy40MDA3IDIyLjQ2OTYgMTIuNzkxNSAyMS43OTcgMTIuNTM4NiAyMS41MzkxTDExLjMxMTUgMjAuMjI0MUMxMC43NTAzIDE5LjU5ODIgOS41MTQ1OSAxNy44NTQ4IDEwLjExNzEgMTUuODk2MUMxMC4zNDk3IDE1LjE0MjIgMTAuODM4OSAxNC4zNDA0IDExLjU0OTEgMTMuODA5OUMxMy4wNDgxIDEyLjY5MyAxNC42NzgzIDEyLjUwOSAxNi4yMzAzIDEyLjk1NDVDMTcuNzM5NCAxMy4zODk3IDE4LjY1OTcgMTQuMjQ3OSAxOS41NTUxIDE1LjA4MjlDMTkuODUxMiAxNS4zNTkgMjAuMTQ0NSAxNS42MzI2IDIwLjQ1NTUgMTUuODg3NEMyMS4xNTUyIDEzLjgzMzkgMjIuMTI2MyAxMS44MjIyIDIzLjU4NiAxMC4xMjYyWiIgZmlsbD0iIzFBMTcxQiIvPgo8L3N2Zz4K
  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Apps & Services"
      content: "PHP 7.2<br/>MySQL 10.2"
    - heading: "Requirements"


# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: git://github.com/platformsh/template-symfony3.git@master
  config: null
  files: []
  profile: Symfony 3
