tests:
    "The homepage should be fast":
        path:
            - "/"
        assertions:
            - "main.wall_time <= 250ms"

scenarios: |
    #!blackfire-player
    name "Flask Scenarios"
    group homepage
        visit url("/")
            name "Home"
            expect status_code() == 200

    scenario
        name "Anonymous Visit"
        include homepages
