version: 1

info:
  id: platformsh/microprofile-helidon
  name: Helidon
  description: |
     <p>This project provides a starter kit for Helidon Eclipse MicroProfile projects hosted on Platform.sh.  It includes a minimalist application skeleton that is intended for you to use as a starting point and modify for your own needs, along with the Platform.sh Config Reader to simplify accessing Platform.sh environment variables.</p>
     <p>Helidon is a collection of Java libraries for writing microservices that run on a fast web core powered by Netty.</p>
     <p>Helidon is designed to be simple to use, with tooling and examples to get you going quickly. Since Helidon is just a collection of libraries running on a fast Netty core, there is no extra overhead or bloat.</p>
  class: experimental
  tags:
  - Java
  - MicroProfile
  - Maven
  image: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='196.79' height='225'%3E%3Cdefs%3E%3Cstyle%3E.cls-1%7Bfill:%23999%7D.cls-2%7Bfill:%23666%7D%3C/style%3E%3C/defs%3E%3Cg %3E%3Cg %3E%3Cpath d='M0 0h98.64v112.63z'/%3E%3Cpath class='cls-1' d='m98.64 0 57.18 65.5-2.71 3.15H98.54z'/%3E%3Cpath class='cls-2' d='m133.27 39.57 10.82-9.19h34.15V40l-22.42 25.5z'/%3E%3Cpath d='M178.24 30.38h8.37L178.24 40z' style='fill:%23333'/%3E%3Cpath d='m178.24 40-25.13 28.65h25.11z' style='fill:%23e6e6e6'/%3E%3Cpath d='M178.22 68.65H98.54v66.46z' style='fill:%23b3b3b3'/%3E%3Cpath class='cls-2' d='M98.64 112.63v22.51H86.33v-11.27l-13.39 10.94V115L48.8 134.81v-11.07l-13.72 11.07H17.44l58.61-47.94z'/%3E%3Cpath class='cls-1' d='m35.08 134.81 13.72-11.07v11.07L72.94 115v19.82l13.39-10.94v11.27zM125.32 112.67l41.57-34.41 29.9 34.34z'/%3E%3Cpath d='m109.77 125.52 15.55-12.85h71.42V225z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E
  notes:
    - heading: "Features"
      content: |
          Java 11<br />
          Automatic TLS certificates<br />
          Maven-based build<br />

initialize:
  repository: https://github.com/platformsh-templates/microprofile-helidon.git@master
  config: null
  files: []
  profile: MicroProfile
